import React from 'react';
import { useTruckStore } from '../../store/useTruckStore';
import { ShieldAlert, Lock, FileCheck, Scale } from 'lucide-react';

export const LegalView: React.FC = () => {
  const { activeLegalTab, openLegalTab, setActiveView } = useTruckStore();

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between border-b border-slate-200 pb-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Legal Information & Disclaimers</h1>
          <p className="text-xs text-slate-500">Mandatory compliance & user protection disclosures.</p>
        </div>
        <button
          onClick={() => setActiveView('calculator')}
          className="text-xs font-semibold text-blue-600 hover:text-blue-700"
        >
          ← Return to Calculator
        </button>
      </div>

      {/* Tabs */}
      <div className="flex space-x-2 border-b border-slate-200 pb-2">
        <button
          onClick={() => openLegalTab('disclaimer')}
          className={`px-4 py-2 rounded-md text-xs font-semibold transition-colors flex items-center space-x-1.5 ${
            activeLegalTab === 'disclaimer'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
          }`}
        >
          <ShieldAlert className="w-4 h-4 text-amber-500" />
          <span>Liability Disclaimer</span>
        </button>

        <button
          onClick={() => openLegalTab('privacy')}
          className={`px-4 py-2 rounded-md text-xs font-semibold transition-colors flex items-center space-x-1.5 ${
            activeLegalTab === 'privacy'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
          }`}
        >
          <Lock className="w-4 h-4" />
          <span>Privacy Policy</span>
        </button>

        <button
          onClick={() => openLegalTab('terms')}
          className={`px-4 py-2 rounded-md text-xs font-semibold transition-colors flex items-center space-x-1.5 ${
            activeLegalTab === 'terms'
              ? 'bg-blue-600 text-white shadow-sm'
              : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
          }`}
        >
          <FileCheck className="w-4 h-4" />
          <span>Terms of Service</span>
        </button>
      </div>

      {/* Content */}
      <div className="bg-white border border-slate-200 rounded-xl p-6 sm:p-8 shadow-sm text-xs sm:text-sm text-slate-700 space-y-4 leading-relaxed">
        {activeLegalTab === 'disclaimer' && (
          <>
            <h2 className="text-lg font-bold text-slate-900">Full Legal & Financial Liability Disclaimer</h2>
            <div className="p-4 bg-amber-50 border border-amber-200 rounded-lg text-amber-950">
              <strong>CRITICAL NOTICE FOR ALL USERS:</strong> Calculations generated by AxleGuard (DOT Bridge Calculator) are provided strictly for mathematical estimation and educational convenience.
            </div>
            <p>
              1. <strong>Weigh Station Supremacy:</strong> Certified state and federal scale equipment located at official DOT weigh stations and portable law enforcement scales remain the <strong>sole and final legal authority</strong> regarding commercial vehicle weight compliance, fines, citations, or out-of-service orders.
            </p>
            <p>
              2. <strong>No Legal Warranty:</strong> While our mathematical engine adheres directly to statutory Federal Bridge Formula B ($W = 500 \times [LN/(N-1) + 12N + 36]$) and applies downward 500 lb rounding rules mandated by 23 CFR § 658.17, local road conditions, temporary bridge closures, state emergency orders, and tire manufacturer load limits may alter actual legal limits on any given highway.
            </p>
            <p>
              3. <strong>Indemnification:</strong> The developers, owners, and operators of AxleGuard disclaim all liability for any traffic citations, overweight fines, scale fees, vehicle damage, or commercial delivery delays resulting from reliance upon this application.
            </p>
          </>
        )}

        {activeLegalTab === 'privacy' && (
          <>
            <h2 className="text-lg font-bold text-slate-900">Privacy Policy</h2>
            <p>
              AxleGuard respects your privacy. We do not store, log, or transmit personal driver telemetry, GPS coordinates, or scale ticket inputs to external servers. All truck calculations run entirely client-side within your web browser.
            </p>
            <p>
              <strong>Google AdSense & Third-Party Cookies:</strong> This application utilizes Google AdSense to serve non-intrusive transportation-related advertisements. Google may use cookies to serve ads based on prior web visits. You may opt out of personalized advertising by visiting Google Ads Settings.
            </p>
          </>
        )}

        {activeLegalTab === 'terms' && (
          <>
            <h2 className="text-lg font-bold text-slate-900">Terms of Service</h2>
            <p>
              By accessing AxleGuard, you agree to utilize the calculator solely for estimation purposes in accordance with federal and local traffic laws. Commercial drivers remain fully responsible for verifying their vehicle scale weights at certified CAT Scale locations prior to highway travel.
            </p>
          </>
        )}
      </div>
    </div>
  );
};
